# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b32eca258cc83d87b0876256fa7b1fba8662ce73f6cbc0a66a4646622a38bd42ca9ca9f0ba5c5e7a2da73636d86ec2495d60ba8928c0478593f8b6bc0292785f

test:
  secret_key_base: 9a55d265dd3d14cfadf1726f33bdb11c01dd803e8cf8fa55cb5a89c9bad9f3ed06983bbcbbfa0111a55ab7655cbbe6f7c66cdb8369c25fcfe87521ac792f6c0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
